### ISSUE TITLE
manim: error: unrecognized arguments: --video_output_dir

### ISSUE THREAD

**Issue by karthik-sivadas** [VAlgoLang/VAlgoLang#158]
While trying to compile .val I am getting this error.

```
Compiling...
Generating animation...
usage: manim file [flags] [scene [scene ...]]
       manim {cfg,init,plugins} [opts]
manim: error: unrecognized arguments: --video_output_dir 7bcdb9c6-2fc4-411f-b50c-2cc217d3e193
Animation could not be generated
```
Has anyone faced this issue or have an idea how to resolve this ?

**Comment by mayanksharma3** [comment]
Hey! Thanks for trying ValgoLang!

The documentation is unfortunately a bit out of date, we'll update that and add some more detailed instructions.

Could you try uninstalling manim (just `pip3 uninstall manim`) and instead install manimlib `pip3 install manimlib`?

That should hopefully work better with VAlgoLang.

We'll make sure to update it to the new manim version as soon as we can!

**Comment by karthik-sivadas** [comment]
Thank you so much for such a quick response.
I had tried that initially but it was throwing this error
```
java.io.IOException: Cannot run program "manim": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.valgolang.animation.ManimProjectWriter.generateAnimation(ManimProjectWriter.kt:49)
	at com.valgolang.CompilerKt.compile(Compiler.kt:103)
	at com.valgolang.CompilerKt.access$compile(Compiler.kt:1)
	at com.valgolang.DSLCommandLineArguments.call(Compiler.kt:191)
	at com.valgolang.DSLCommandLineArguments.call(Compiler.kt:138)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at com.valgolang.CompilerKt.main(Compiler.kt:196)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 14 more
```

That's the reason for installing `manim`.
Is there any command or way I can directly use the docker image for creating video.
And I don't mind updating the documentation if someone can guide me.

**Comment by mayanksharma3** [comment]
Yeah so what has happened is since we developed this manim has changed a bit and changed to this overall "manim" package. We need to do some porting over to that which may take some time but luckily the original package we used should still work.

So if you go ahead an install manimlib with `pip3 install manimlib` (after uninstalling the manim you have installed) the manim command will come up again but this time will be right "right manim".

Try running that command and if it doesn't work let us know and we can help you out!

**Comment by karthik-sivadas** [comment]
As suggested by you I tried. manim command after installing manimlib but it shows `zsh: command not found: manim`.

**Comment by mayanksharma3** [comment]
Hmm that's interesting, it might be that the package is not in the path. For example, I get this issue sometimes like below:

```
  WARNING: The script manim is installed in '/Users/mayank/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

In which case you might need to add a directory to your path.

Try looking at `python3 -m site` which should show you a list of directories, one of them should hold manim in there and try to add that to the path and see if that works

**Comment by karthik-sivadas** [comment]
I tried the above suggestion too. Add my path as `export PATH="/Users/karthiksivadas/Library/Python/3.9:$PATH"` its still not working. Is there a way I can use the docker?

**Comment by mayanksharma3** [comment]
Could you please try:

`export PATH="/Users/karthiksivadas/Library/Python/3.9/bin:$PATH"`

It requires the bin folder which has all the executables.

The docker method is an option but is a bit fiddly as it's a container so all the files you want compiled need to be mounted in a way such that docker can see them.

**Comment by karthik-sivadas** [comment]
<img width="802" alt="Screenshot 2021-03-19 at 8 17 51 PM" src="https://user-images.githubusercontent.com/6113982/111798659-48cf3600-88f0-11eb-8bf7-544c28bd2bf8.png">
Still no progress

**Comment by mayanksharma3** [comment]
Okay no worries I'll try to build up a neat command to use docker for it! 

It's strange though as I've got people testing the `pip3 install manimlib` command and it seems to have the manim file installed as `/usr/local/bin/manim`

I'll let you know when the docker command is ready and I'll update here

**Comment by karthik-sivadas** [comment]
Thank you very much 🙇

**Comment by mayanksharma3** [comment]
Alright let's try this out:

`docker run --rm  -v "$PWD:$PWD" valgolang/valgolang $PWD/<FILENAME>.val -o=$PWD/out.mp4`

It's a little dodgy in terms of how things are moved around inside and outside the container but steps are:

1. Go to the folder containing the .val file
2. Run the command above replacing `<FILENAME>` with the name of your .val file **(the first time will take a while to pull the image from docker hub)**
3. The output should then be a file called `out.mp4` in the same folder
4. If you want to add any more options from the CLI arguments, go ahead and add them at the end of that docker command

Let me know if that works for you!

**Comment by karthik-sivadas** [comment]
It worked like a charm. Thank you very much.
