### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by faisalaljishi** [VAlgoLang/VAlgoLang#161]
I cannot seem to set up the project, as running gradlew build -x test returns an error with './antlrBuild'. 

running 'docker build . ' also returns the same issue.

`  > Configure project :
      Compiling Antlr Parser
      
      Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
      Use '--warning-mode all' to show the individual deprecation warnings.
      See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings
      <-------------> 0% WAITING
      > IDLE
      
      FAILURE: Build failed with an exception.
      
      * What went wrong:
      A problem occurred evaluating root project 'valgolang'.
      > A problem occurred starting process 'command './antlrBuild''
      
      * Try:
      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
      
      * Get more help at https://help.gradle.org
      The command '/bin/sh -c gradle build -x test' returned a non-zero code: 1`

**Comment by mayanksharma3** [comment]
Hey, thanks for trying out ValgoLang!

It seems the ANTLR parser was not building correctly, could you try running `sh ./antlr_config/antlrBuild` and paste the output here?

We can then work out better what's going wrong there.

(I'll check docker too and see if I can reproduce that locally as well)

**Comment by faisalaljishi** [comment]
I am currently on windows, which I thought was perhaps the issue with the shell script not running, so I thought docker would run the shell script and that would fix the issue. Running using MINGW64 `sh ./antlr_config/antlrBuild` returns the following:
 
```
MINGW64 ~/IdeaProjects/VAlgoLang (master)
$ sh ./antlr_config/antlrBuild
Compiling the lexer..
Compiling the parser..
```

**Comment by mayanksharma3** [comment]
Okay nice I think that has worked through git bash. Can you check there is now a src/main/java folder (along with the src/main/kotlin folder)?

If it has maybe try running the gradle command through git bash too?

We do need to make the antlrBuild platform agnostic as we only ran this on Mac and Linux. 

@arj119 could you possibly look into that if you're free?

**Comment by mayanksharma3** [comment]
This has now been fixed, running the command locally on windows should now work (without needing git bash), and docker running should also work on windows.

Let us know if something still doesn't work!
